# .github/workflows/release.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # 當推送到任何分支時觸發
    tags:
      - 'v*.*.*'  # 當推送匹配這個模式的標籤時觸發，例如 v1.0.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison cmake llvm clang build-essential libfl-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DFLEX_EXECUTABLE=/usr/bin/flex -DFLEX_INCLUDE_DIR=/usr/include -DFLEX_LIBRARY=/usr/lib/x86_64-linux-gnu/libfl.so

      - name: Build the project
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest

  release:
    permissions: write-all
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison cmake llvm clang build-essential libfl-dev zip

      - name: Configure CMake
        run: |
          cmake -S . -B build -DFLEX_EXECUTABLE=/usr/bin/flex -DFLEX_INCLUDE_DIR=/usr/include -DFLEX_LIBRARY=/usr/lib/x86_64-linux-gnu/libfl.so

      - name: Build the project
        run: cmake --build build
      - name: Package executable
        run: |
          cd build
          zip cpoke.zip cpoke
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/poke.zip
          asset_name: poke.zip
          asset_content_type: application/zip
